---
- name: Restart SkillNet
  ansible.builtin.docker_container:
    name: "{{ skillnet_container_name }}"
    state: started
    restart: true
  when: skillnet_enabled | bool
  listen: restart skillnet
