[local]
localhost ansible_connection=local

[macos]
macbook-pro-m1pro ansible_host=127.0.0.1 ansible_connection=local

[registries:children]
local

[security:children]
local

[communications:children]
local

[agents:children]
local
macos
