replicaCount: 1

image:
  repository: noesislab/ans
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsUser: 1000
  runAsGroup: 1000

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ans.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

env:
  ANS_PORT: "8080"
  ANS_LOG_LEVEL: "info"

envFromSecrets: []
#  - name: ANS_API_KEY
#    secretName: ans-secrets
#    key: api-key
