---
- name: Restart muxd-hub
  ansible.builtin.systemd:
    name: muxd-hub
    state: restarted
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_uid }}/bus"
  listen: restart muxd-hub

- name: Restart muxd-daemon
  ansible.builtin.systemd:
    name: muxd
    state: restarted
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_uid }}/bus"
  listen: restart muxd-daemon

- name: Restart all muxd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_user_uid }}/bus"
  loop:
    - muxd-hub
    - muxd
  listen: restart muxd
